### ISSUE TITLE
Image not showing in 4.2.2.a

### ISSUE THREAD

**Issue by perry0513** [lf-lang/lf-pico#13]
In section 4.2 in lab "Interfacing with Sensors", there is a line saying
`<img src="img/AccelerometerDisplay.png" alt"AccelerometerDisplay diagram"/>`
which indicates a missing image. A screenshot is shown below. Can anyone fix this?
<img width="748" alt="Screen Shot 2023-08-22 at 1 46 04 PM" src="https://github.com/lf-lang/embedded-lab/assets/31507162/6b2300ba-6fe1-4da3-a7ce-3d81c7fd2aec">

**Comment by edwardalee** [comment]
Fixed!  Thanks for pointing it out.
